AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EC2ProducerKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the the producer instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  EC2ProducerInstanceType:
    Description: EC2 Producer instance type
    Type: String
    Default: c5.2xlarge
    AllowedValues: [a1.2xlarge , a1.4xlarge , a1.large , a1.medium , a1.metal , a1.xlarge , c1.medium , c1.xlarge , c3.2xlarge , c3.4xlarge , c3.8xlarge , c3.large , c3.xlarge , c4.2xlarge , c4.4xlarge , c4.8xlarge , c4.large , c4.xlarge , c5.12xlarge , c5.18xlarge , c5.24xlarge , c5.2xlarge , c5.4xlarge , c5.9xlarge , c5.large , c5.metal , c5.xlarge , c5a.12xlarge , c5a.16xlarge , c5a.24xlarge , c5a.2xlarge , c5a.4xlarge , c5a.8xlarge , c5a.large , c5a.xlarge , c5ad.12xlarge , c5ad.16xlarge , c5ad.24xlarge , c5ad.2xlarge , c5ad.4xlarge , c5ad.8xlarge , c5ad.large , c5ad.xlarge , c5d.12xlarge , c5d.18xlarge , c5d.24xlarge , c5d.2xlarge , c5d.4xlarge , c5d.9xlarge , c5d.large , c5d.metal , c5d.xlarge , c5n.18xlarge , c5n.2xlarge , c5n.4xlarge , c5n.9xlarge , c5n.large , c5n.metal , c5n.xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  EC2ConsumerKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the consumer instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  EC2ConsumerInstanceType:
    Description: EC2 Consumer instance type
    Type: String
    Default: c5.2xlarge
    AllowedValues: [a1.2xlarge , a1.4xlarge , a1.large , a1.medium , a1.metal , a1.xlarge , c1.medium , c1.xlarge , c3.2xlarge , c3.4xlarge , c3.8xlarge , c3.large , c3.xlarge , c4.2xlarge , c4.4xlarge , c4.8xlarge , c4.large , c4.xlarge , c5.12xlarge , c5.18xlarge , c5.24xlarge , c5.2xlarge , c5.4xlarge , c5.9xlarge , c5.large , c5.metal , c5.xlarge , c5a.12xlarge , c5a.16xlarge , c5a.24xlarge , c5a.2xlarge , c5a.4xlarge , c5a.8xlarge , c5a.large , c5a.xlarge , c5ad.12xlarge , c5ad.16xlarge , c5ad.24xlarge , c5ad.2xlarge , c5ad.4xlarge , c5ad.8xlarge , c5ad.large , c5ad.xlarge , c5d.12xlarge , c5d.18xlarge , c5d.24xlarge , c5d.2xlarge , c5d.4xlarge , c5d.9xlarge , c5d.large , c5d.metal , c5d.xlarge , c5n.18xlarge , c5n.2xlarge , c5n.4xlarge , c5n.9xlarge , c5n.large , c5n.metal , c5n.xlarge]
    ConstraintDescription: must be a valid EC2 instance type.  
  S3BucketName:
    Description: S3 bucket name
    Type: String  
  DynamoDBReadCapacityUnits:
    Description: DynamoDB Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  DynamoDBWriteCapacityUnits:
    Description: DynamoDB Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  RDSInstanceName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  RDSUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  RDSPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.  
  ApiGatewayName:
    Type: String
    Default: my-api
Resources:
  EC2Producer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/EC2Instance_Producer.yaml'
      Parameters:
         KeyName:
          Ref: EC2ProducerKeyName 
         InstanceType:
          Ref: EC2ProducerInstanceType 
           
  EC2Consumer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/EC2Instance_Consumer.yaml'
      Parameters:
         KeyName:
          Ref: EC2ConsumerKeyName 
         InstanceType:
          Ref: EC2ConsumerInstanceType       
  S3WithLambdaTrigger:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/S3WithLambdaTrigger.yaml'
      Parameters:
         BucketName:
          Ref: S3BucketName              
  DynamoDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/DynamoDB.yaml'    
      Parameters:
        ReadCapacityUnits:
          Ref: DynamoDBReadCapacityUnits
        WriteCapacityUnits:
          Ref: DynamoDBWriteCapacityUnits     
  RDSAurora:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/RDS_MySql.yaml'   
      Parameters:
        DBName:
          Ref: RDSInstanceName
        DBUser:
          Ref: RDSUser
        DBPassword:
          Ref: RDSPassword   
  APIGatewayWithLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cloudformation-stacks-bucket-apn.s3.us-east-2.amazonaws.com/APIGatewayWithLambda.yaml'   
      